# Generated by Django 5.2.4 on 2025-07-09 14:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('Food', 'Food'), ('Movies', 'Movies'), ('Travel', 'Travel'), ('Bills', 'Bills'), ('Other', 'Other')], max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
